config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get 'about', to: 'pages#about'
  
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimu: 6, maximum: 100}
    validates :description, presence:true , length: { minimum:10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase}
    has_many :articles
    validates :username, presence: true, 
                         uniqueness: {case_sensitive: false}, 
                         length: { minimum: 3, maximum: 25}
   
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i                        
    validates :email, presence: true,  
                      uniqueness: {case_sensitive: false}, 
                      length: { maximum: 105},
                      format: { with: VALID_EMAIL_REGEX}

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show
    end

    def index
      @articles = Article.all 
    end

    def new
      @article = Article.new 
    end

    def edit 
    end

    def create
      @article = Article.new(article_params)
      @article.user = User.first
      if @article.save
        flash[:notice] = "Article was created succesfully."
        redirect_to @article
      else 
        render 'new'
      end 
    end 

    def update 
      if @article.update(article_params)
        flash[:notice] = "Article was updated succesfully."
        redirect_to @article
      else
        render 'edit'      
      end
    end

    def destroy
      @article.destroy
      redirect_to articles_path
    end

    private 

     def set_article 
       @article = Article.find(params[:id])
     end

     def article_params
       params.require(:article).permit(:title, :description)
     end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    def show
        @user = User.find(params[:id])
        @articles = @user.articles
    end

    def index
        @users = User.all 
    end

    def new
        @user = User.new
    end

    def edit
        @user= User.find(params[:id])
    end

    def update
        @user= User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated."
            redirect_to @user
        else
            render 'edit'
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have succesfully signed up"
            redirect_to articles_path
        else
            render 'new'
        end
       
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end

end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
          <div class="card-header fst-italic">
            <% if article.user%>
              By: <%= link_to article.user.username, user_path(article.user)%>
            <%end%>
          </div>
          <div class="card-body">
            <h5 class="card-title" > <%= link_to "#{article.title}", article_path(article), class: "text-success ", id:"Article_title" %></h5>
            <p class="card-text "><%= truncate(article.description, length: 100) %></p>
            <a><%= link_to 'View', article_path(article), method: :get, class: "btn btn-outline-success"%></a>
            <a><%= link_to 'Edit', edit_article_path(article), method: :get, class:"btn btn-outline-primary"%></a>
            <a><%= link_to 'Delete', article_path(article), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" }, class:"btn btn-outline-danger" %> </a>
          </div>
          <div class="card-footer text-muted">
            <Small> Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</Small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj:@article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", data: {turbo: false}, local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg col-5 mt-4" %>
        </div>
      <% end %>
    </div>
    
    
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info text-center mb-2" %>
   
  </div>

</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4"> Edit Articles </h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4"> Listing All Articles </h1>

<%= render 'article' %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4"> Create a New Article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"> <%=@article.title%></h1>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-body rounded">
                <div class="card-header fst-italic">
                    By: <%= @article.user.username if @article.user%>
                    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                </div>
                <div class="card-body">
                    <p class="card-text "><%= simple_format(@article.description) %></p>
                    <a><%= link_to 'Edit', edit_article_path(@article), method: :get, class:"btn btn-outline-primary"%></a>
                    <a><%= link_to 'Delete', article_path(@article), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" }, class:"btn btn-outline-danger" %> </a>
                </div>
                <div class="card-footer text-muted">
                    <Small> Created <%= time_ago_in_words(@article.created_at) %> ago, 
                    edited <%= time_ago_in_words(@article.updated_at) %> ago</Small>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_darknavbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class:"nav-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create new article", new_article_path, class: "dropdown-item" %></li>
            <li><%= link_to "View articles", articles_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="footer mt auto py-4 bg-dark text-white">
  <div class="foot text-center">
    <span class="text-muted">Copyright &copy; Erion Technologies.</span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>  
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">

    <%= render 'layouts/darknavbar'%>

    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer'%>
    
  </body>
</html>

app/views/pages/about.html.erb
<p>This is about page</p>

<%= link_to 'Articles listing', articles_path %>|
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class = "container" id="home-container">

    <div class="jumbotron bg-dark text-light p-5 text-center" >
        <h1 class="display-4">Alpha Blog</h1>
        <hr>
        <p>Go to My Website</p>
        <%=link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
    </div>
    
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %> 
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul> 
        <% obj.errors.full_messages.each do |msg| %> 
        <li><%= msg %></li> 
        <% end %> 
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", data: {turbo: false}, local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter Username" %>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        
        <div class="form-group row mt-4">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg col-5 mt-4") %>
        </div>
      <% end %>
    </div>
    
    
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info text-center mb-2" %>
   
  </div>

</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4"> Alpha Bloggers </h1>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
          <div class="card-header fst-italic">
            <%= link_to user.username, user%>
          </div>
          <div class="card-body">
            <h5 class="card-title" >
                <%= link_to gravatar_for(user, size: 150),user %>
            </h5>
            <p class="card-text "><%=  pluralize(user.articles.count, "article") %></p>
            <a><%= link_to 'View profile', user, method: :get, class: "btn btn-outline-success"%></a>
            <a><%= link_to 'Edit profile', edit_user_path(user), method: :get, class:"btn btn-outline-primary"%></a>
          </div>
          <div class="card-footer text-muted">
            <Small> Joined <%= time_ago_in_words(user.created_at) %> ago</Small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4"> Sign Up for Alpha Blog </h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username  %>'s profile</h1>

<%= gravatar_for @user, size: 200  %>

<div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class:"btn btn-outline-primary"%>
</div>

<h3 class="text-center mt-4">Articles</h3>

<%= render 'articles/article'  %>